version: "3.8"
services:
  mysql-db:
    image: mysql:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mingeso12023
    ports:
      - 33060:3306
  app:
    container_name: pep1_mingeso_docker
    image: aldo564/pep1_mingeso_docker
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/mingeso12023?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db